version: "3.8"

networks:
  steam-net:
    driver: bridge
  database:
    driver: bridge

services:
  steam-backend:
    container_name: steam-backend
    # image: yenyeny1/steam-backend:1.0
    build: ./backend/steam/
    volumes:
      - ./images:/app/images
    restart: always
    ports:
      - 8080:8080
    networks:
      - database
      - steam-net
    depends_on:
      - steam-db 
    environment:
      - TZ=Asia/Seoul

  frontend:
    container_name: steam-front
    # image: shingyeongjun/steam-front:latest
    build: ./frontend/
    volumes:
      - ./images:/app/public/assets/images
    restart: on-failure
    ports:
      - 3000:3000
    networks:
      - steam-net
    environment:
      - TZ=Asia/Seoul

  steam-db:
    container_name: steam-db
    image: mysql:latest
    restart: always
    ports: 
      - 3306:3306
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --range_optimizer_max_mem_size=16777216
    environment:
      MYSQL_DATABASE : steam
      MYSQL_USER: steam
      MYSQL_PASSWORD: steam
      MYSQL_ROOT_PASSWORD: steam
    networks:
    - database

  steam-nginx:
    container_name: steam-nginx
    image: nginx:mainline-alpine3.18-slim
    restart: always
    ports: 
      - "80:80/tcp"
      - "443:443"
    networks:
      - steam-net
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=Asia/Seoul