# 공통 설정
server:
  tomcat:
    max-http-form-post-size: 10GB

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

spring:
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

# test 프로파일 설정
---
spring:
  config:
    activate:
      on-profile: "test"
  datasource:
    url: jdbc:h2:tcp://localhost/~/steam
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

# dev 프로파일 설정
---
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:mysql://steam-db:3306/steam?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: steam
    password: steam
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect