spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/steam
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

server:
  tomcat:
    max-http-form-post-size: 10GB


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace